#!/usr/bin/env bash

ENABLE_GPU=true

ENABLE_PYTHON=false
PYTHON_VERSION=2

ENABLE_DL_ALL=false

ENABLE_TENSORFLOW=false
ENABLE_THEANO=false
ENABLE_PYTORCH=false
ENABLE_KERAS=false
ENABLE_DMLC=false
ENABLE_CAFFE=false
ENABLE_CAFFE2=false
ENABLE_TORCH=false
